services:
  autoflex-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=autoflex
    volumes:
      - ./docker:/docker-entrypoint-initdb.d

  autoflex-api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - autoflex-pg